<a href="https://colab.research.google.com/github/salimdo2004/Pr-diction-des-Maladies-Cardiaques-par-Machine-Learning-/blob/main/7_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.cluster import KMeans
import pickle

In [2]:
import pandas as pd

data1 = pd.read_csv("Breast_Cancer.csv")
data2 = pd.read_csv("brca.csv")
data3 = pd.read_csv("diabetes.csv")
data4 = pd.read_csv("heart.csv")
data5 = pd.read_csv("heart_disease.csv")
data6 = pd.read_csv("medications.csv", encoding="latin-1")
data7 = pd.read_csv("sepsis_icu_synthetic.csv")
data8 = pd.read_csv("vitamin_deficiency_disease_dataset_20260123.csv")

heart_df = pd.concat([data4, data5], ignore_index=True)
diabetes_df = data3
cancer_df = pd.concat([data1, data2], ignore_index=True)
sepsis_df = data7
vitamin_df = data8

In [3]:
cancer_df.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,...,x.texture_worst,x.perimeter_worst,x.area_worst,x.smoothness_worst,x.compactness_worst,x.concavity_worst,x.concave_pts_worst,x.symmetry_worst,x.fractal_dim_worst,y
0,68.0,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50.0,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,58.0,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,58.0,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,47.0,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
cancer_df.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status', 'Unnamed: 0',
       'x.radius_mean', 'x.texture_mean', 'x.perimeter_mean', 'x.area_mean',
       'x.smoothness_mean', 'x.compactness_mean', 'x.concavity_mean',
       'x.concave_pts_mean', 'x.symmetry_mean', 'x.fractal_dim_mean',
       'x.radius_se', 'x.texture_se', 'x.perimeter_se', 'x.area_se',
       'x.smoothness_se', 'x.compactness_se', 'x.concavity_se',
       'x.concave_pts_se', 'x.symmetry_se', 'x.fractal_dim_se',
       'x.radius_worst', 'x.texture_worst', 'x.perimeter_worst',
       'x.area_worst', 'x.smoothness_worst', 'x.compactness_worst',
       'x.concavity_worst', 'x.concave_pts_worst', 'x.symmetry_worst',
       'x.fractal_dim_worst', 'y'],
      dtype='object')

***Heart Disease***

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
heart_df["sex"] = le.fit_transform(heart_df["sex"])

In [6]:
heart_df = pd.get_dummies(heart_df, drop_first=True)

In [7]:
X = heart_df.drop("target", axis=1)
y = heart_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
y.isnull().sum()
heart_df = heart_df.dropna(subset=["target"])

In [9]:
X = heart_df.drop("target", axis=1)
y = heart_df["target"]

In [10]:
print(y.isnull().sum())  # doit être 0

0

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

***Random Forest***

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

RandomForestClassifier()

In [13]:
X.isnull().sum()

age                              0
sex                              0
cp                               0
trestbps                         0
chol                             0
fbs                              0
restecg                          0
thalach                          0
exang                            0
oldpeak                          0
slope                            0
ca                               0
thal                             0
Age                           1025
Blood Pressure                1025
Cholesterol Level             1025
BMI                           1025
Sleep Hours                   1025
Triglyceride Level            1025
Fasting Blood Sugar           1025
CRP Level                     1025
Homocysteine Level            1025
Gender_Male                      0
Exercise Habits_Low              0
Exercise Habits_Medium           0
Smoking_Yes                      0
Family Heart Disease_Yes         0
Diabetes_Yes                     0
High Blood Pressure_Yes          0
Low HDL Cholesterol_Yes          0
High LDL Cholesterol_Yes         0
Alcohol Consumption_Low          0
Alcohol Consumption_Medium       0
Stress Level_Low                 0
Stress Level_Medium              0
Sugar Consumption_Low            0
Sugar Consumption_Medium         0
Heart Disease Status_Yes         0
dtype: int64

In [14]:
X.isnull().sum().sum()

np.int64(9225)

In [15]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['Age' 'Blood Pressure' 'Cholesterol Level' 'BMI' 'Sleep Hours'
 'Triglyceride Level' 'Fasting Blood Sugar' 'CRP Level'
 'Homocysteine Level']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['Age' 'Blood Pressure' 'Cholesterol Level' 'BMI' 'Sleep Hours'
 'Triglyceride Level' 'Fasting Blood Sugar' 'CRP Level'
 'Homocysteine Level']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train_scaled, y_train)

SVC()

In [18]:
kmeans = KMeans(n_clusters=2)
kmeans.fit(X_train_scaled)

KMeans(n_clusters=2)

In [19]:
#pickle.dump(rf, open("heart_model.pkl", "wb"))
#pickle.dump(scaler, open("heart_scaler.pkl", "wb"))

***diabetes_df***

***Séparer X / y***

In [20]:
X = diabetes_df.drop("Outcome", axis=1)
y = diabetes_df["Outcome"]

Scaling

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Train / Test split

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

svm

In [24]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train, y_train)

SVC()

In [25]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2)
kmeans.fit(X_scaled)

KMeans(n_clusters=2)

In [26]:
from sklearn.metrics import accuracy_score

rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.7402597402597403

In [27]:
import pickle

#pickle.dump(rf, open("diabetes_model.pkl", "wb"))
#pickle.dump(scaler, open("diabetes_scaler.pkl", "wb"))

cancer

In [28]:
cancer_df = cancer_df.drop(columns=["Unnamed: 0"])

Séparer X / y

In [29]:
X = cancer_df.drop("y", axis=1)
y = cancer_df["y"]

Encoding

In [30]:
from sklearn.preprocessing import LabelEncoder

for col in X.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

scaling

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

train / test

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [33]:
import numpy as np

np.isnan(X_train).sum()

np.int64(98970)

In [34]:
# 1. Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [35]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [36]:
import numpy as np

print("NaN dans X_train :", np.isnan(X_train).sum())
print("NaN dans X_test :", np.isnan(X_test).sum())

NaN dans X_train : 0
NaN dans X_test : 0

In [37]:
X.isnull().sum().sum()

np.int64(123565)

In [38]:
import numpy as np

# Nettoyage global
X = X.replace(["?", "NA", "null", " "], np.nan)

# Forcer types numériques
import pandas as pd
for col in X.columns:
    try:
        X[col] = pd.to_numeric(X[col])
    except:
        pass

In [39]:
import pandas as pd

# Vérifier NaN dans X original
print("NaN dans X avant pipeline :")
print(X.isnull().sum())

# Vérifier y
print("NaN dans y :", pd.isnull(y).sum())

NaN dans X avant pipeline :
Age                        569
Race                         0
Marital Status               0
T Stage                      0
N Stage                      0
6th Stage                    0
differentiate                0
Grade                        0
A Stage                      0
Tumor Size                 569
Estrogen Status              0
Progesterone Status          0
Regional Node Examined     569
Reginol Node Positive      569
Survival Months            569
Status                       0
x.radius_mean             4024
x.texture_mean            4024
x.perimeter_mean          4024
x.area_mean               4024
x.smoothness_mean         4024
x.compactness_mean        4024
x.concavity_mean          4024
x.concave_pts_mean        4024
x.symmetry_mean           4024
x.fractal_dim_mean        4024
x.radius_se               4024
x.texture_se              4024
x.perimeter_se            4024
x.area_se                 4024
x.smoothness_se           4024
x.compactness_se          4024
x.concavity_se            4024
x.concave_pts_se          4024
x.symmetry_se             4024
x.fractal_dim_se          4024
x.radius_worst            4024
x.texture_worst           4024
x.perimeter_worst         4024
x.area_worst              4024
x.smoothness_worst        4024
x.compactness_worst       4024
x.concavity_worst         4024
x.concave_pts_worst       4024
x.symmetry_worst          4024
x.fractal_dim_worst       4024
dtype: int64
NaN dans y : 4024

In [40]:
y = y.fillna(y.mode()[0])

In [41]:
X = X.fillna(0)

***Scaling***

In [42]:
import numpy as np

print("NaN dans X_train_scaled :", np.isnan(X_train_scaled).sum())

NaN dans X_train_scaled : 0

In [43]:
import pandas as pd

y_train = pd.Series(y_train).fillna(pd.Series(y_train).mode()[0])

In [44]:
print(type(y_train))
print(set(y_train))

<class 'pandas.core.series.Series'>
{'B', 'M'}

In [45]:
y = ["Yes", "No", "Yes", None]

In [46]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [47]:
import numpy as np

print("NaN X :", np.isnan(X_train_scaled).sum())
print("NaN y :", np.isnan(y_train).sum())

NaN X : 0
NaN y : 0

In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)

RandomForestClassifier()

In [49]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [50]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train_scaled, y_train)

SVC()

In [51]:
import numpy as np

print(np.isnan(X_scaled).sum())

123565

In [52]:
X_scaled = np.nan_to_num(X_scaled)

In [53]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2)
kmeans.fit(X_scaled)

KMeans(n_clusters=2)

In [54]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)   # AVANT split

In [55]:
print(pd.Series(y_test).unique())
print(pd.Series(y_test).dtype)

[nan 'M' 'B']
object

In [56]:
import pickle

pickle.dump(rf, open("cancer_model.pkl", "wb"))
pickle.dump(scaler, open("cancer_scaler.pkl", "wb"))

In [57]:
sepsis_df = data7
vitamin_df = data8

In [61]:
df = sepsis_df   # ou vitamin_df

In [64]:
print(df.columns)

Index(['subject_id', 'age', 'gender', 'weight_kg', 'height_cm', 'bmi',
       'ethnicity', 'insurance', 'hr_mean', 'hr_max', 'hr_min', 'hr_std',
       'sbp_mean', 'sbp_max', 'sbp_min', 'sbp_std', 'dbp_mean', 'dbp_max',
       'dbp_min', 'dbp_std', 'map_mean', 'temp_celsius_mean',
       'temp_celsius_max', 'temp_celsius_min', 'temp_celsius_std', 'spo2_mean',
       'spo2_min', 'spo2_max', 'spo2_std', 'respiratory_rate_mean',
       'respiratory_rate_max', 'respiratory_rate_min', 'respiratory_rate_std',
       'wbc', 'lactate_mmol', 'creatinine', 'platelet_count',
       'bilirubin_total', 'glucose', 'ph_arterial', 'pao2_fio2_ratio', 'inr',
       'sodium', 'potassium', 'chloride', 'bicarbonate', 'hematocrit',
       'hemoglobin', 'diabetes', 'hypertension', 'chf', 'copd',
       'chronic_kidney_disease', 'liver_disease', 'immunosuppression', 'cad',
       'atrial_fibrillation', 'cancer_active', 'vasopressors_flag',
       'mechanical_ventilation', 'fio2_percent', 'antibiotics_24h',
       'fluids_ml_24h', 'sedation_score', 'vasopressor_dose_mcg_kg_min',
       'insulin_infusion_flag', 'sofa_score', 'apache_iv', 'qsofa',
       'sirs_criteria', 'gcs_total', 'icu_los_hours', 'hospital_admit_source',
       'icu_admit_time_hour', 'day_of_week', 'readmission_30day',
       'sepsis_label'],
      dtype='object')

In [65]:
target = "sepsis_label"

X = sepsis_df.drop(columns=[target])
y = sepsis_df[target]

In [71]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
# Colonnes
num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include=['object']).columns

# Pipelines
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine
preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [72]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", RandomForestClassifier())
])

In [73]:
from sklearn.svm import SVC

svm_model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", SVC())
])

In [74]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf_model.fit(X_train, y_train)
svm_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['subject_id', 'age', 'weight_kg', 'height_cm', 'bmi', 'hr_mean',
       'hr_max', 'hr_min', 'hr_std', 'sbp_mean', 'sbp_max', 'sbp_min',
       'sbp_std', 'dbp_mean', 'dbp_max', 'dbp_min', 'dbp_std', 'map_mean',
       'temp_celsius_mean...
       'apache_iv', 'qsofa', 'sirs_criteria', 'gcs_total', 'icu_los_hours',
       'icu_admit_time_hour', 'day_of_week', 'readmission_30day'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'ethnicity', 'insurance', 'hospital_admit_source'], dtype='object'))])),
                ('classifier', SVC())])

In [75]:
from sklearn.metrics import accuracy_score

rf_pred = rf_model.predict(X_test)
svm_pred = svm_model.predict(X_test)

print("RF Accuracy:", accuracy_score(y_test, rf_pred))
print("SVM Accuracy:", accuracy_score(y_test, svm_pred))

RF Accuracy: 1.0
SVM Accuracy: 1.0

In [76]:
from sklearn.cluster import KMeans

# transformer X
X_processed = preprocessor.fit_transform(X)

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X_processed)

clusters = kmeans.labels_

In [77]:
import joblib

joblib.dump(rf_model, "rf_model.pkl")
joblib.dump(svm_model, "svm_model.pkl")
joblib.dump(preprocessor, "preprocessor.pkl")

['preprocessor.pkl']

In [79]:
vitamin_df.columns

Index(['age', 'gender', 'bmi', 'smoking_status', 'alcohol_consumption',
       'exercise_level', 'diet_type', 'sun_exposure', 'income_level',
       'latitude_region', 'vitamin_a_percent_rda', 'vitamin_c_percent_rda',
       'vitamin_d_percent_rda', 'vitamin_e_percent_rda',
       'vitamin_b12_percent_rda', 'folate_percent_rda', 'calcium_percent_rda',
       'iron_percent_rda', 'hemoglobin_g_dl', 'serum_vitamin_d_ng_ml',
       'serum_vitamin_b12_pg_ml', 'serum_folate_ng_ml', 'symptoms_count',
       'symptoms_list', 'has_night_blindness', 'has_fatigue',
       'has_bleeding_gums', 'has_bone_pain', 'has_muscle_weakness',
       'has_numbness_tingling', 'has_memory_problems', 'has_pale_skin',
       'disease_diagnosis', 'has_multiple_deficiencies'],
      dtype='object')

In [80]:
target = "has_multiple_deficiencies"

X = vitamin_df.drop(columns=[target])
y = vitamin_df[target]

In [81]:
X = X.drop(columns=["symptoms_list"])

PREPROCESSING

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Colonnes
num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include=['object']).columns

# Pipelines
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Combine
preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [83]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", RandomForestClassifier())
])

In [84]:
from sklearn.svm import SVC

svm_model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", SVC())
])

In [85]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf_model.fit(X_train, y_train)
svm_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['age', 'bmi', 'vitamin_a_percent_rda', 'vitamin_c_percent_rda',
       'vitamin_d_percent_rda', 'vitamin_e_percent_rda',
       'vitamin_b12_percent_rda', 'folate_percent_rda', 'calcium_percent_rda',
       'iron_percent_rda', '...
       'has_memory_problems', 'has_pale_skin'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['gender', 'smoking_status', 'alcohol_consumption', 'exercise_level',
       'diet_type', 'sun_exposure', 'income_level', 'latitude_region',
       'disease_diagnosis'],
      dtype='object'))])),
                ('classifier', SVC())])

In [86]:
from sklearn.metrics import accuracy_score

rf_pred = rf_model.predict(X_test)
svm_pred = svm_model.predict(X_test)

print("RF Accuracy:", accuracy_score(y_test, rf_pred))
print("SVM Accuracy:", accuracy_score(y_test, svm_pred))

RF Accuracy: 0.98875
SVM Accuracy: 0.95125

In [87]:
import joblib

joblib.dump(rf_model, "rf_vitamin.pkl")
joblib.dump(preprocessor, "preprocessor_vitamin.pkl")

['preprocessor_vitamin.pkl']